import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = { title: "About", description: "Meet Faith Oluwalana, an Information Technology student and product-focused software developer." };

export default function About() {
  return <main className="inner-page about-page"><header className="page-heading"><span className="eyebrow">About</span><h1>I learn by building <em>products people can use.</em></h1></header><div className="about-layout"><div className="about-photo"><Image src="/projects/portrait.png" alt="Faith Oluwalana" fill sizes="(max-width: 850px) 90vw, 35vw" /></div><div className="about-story"><span className="small-label">A little about me</span><p className="about-lead">I&apos;m a full-stack developer and growing data analyst specialising in TypeScript, React, Next.js, Node.js, Python, Power BI and MySQL.</p><p>As an Information Technology student at FUTA, I combine product engineering with data analysis to build responsive, reliable digital products across AI, Web3, learning, market intelligence and business platforms.</p><p>Away from my laptop, I enjoy football, video games and music.</p><Link href="/work" className="inline-link">See what I&apos;ve built ↗</Link></div></div><section className="education"><div className="section-head"><div><span className="eyebrow">Learning / Education</span><h2>Building the foundation.</h2></div></div><div className="education-row"><div><h3>B.Sc. Information Technology</h3><p>Federal University of Technology Akure (FUTA)</p></div><strong>In progress</strong></div><div className="education-row"><div><h3>National Diploma, Computer Science</h3><p>Federal Polytechnic Ado-Ekiti</p></div><strong>2020–2022</strong></div><div className="education-row"><div><h3>Data Analyst Bootcamp 2026</h3><p>Certificate of completion</p><a className="certificate-link" href="/projects/data-analyst-bootcamp.webp" target="_blank" rel="noreferrer">View certificate ↗</a></div><strong>2026</strong></div></section></main>;
}
